# action.yml
name: Pact - Publish Contract
description: Publish a contract on pact broker
inputs:
  directory:
    description: Directory with pact contract files.
    required: true
  consumer_app_version:
    description: The consumer application version.
    required: true
  branch:
    description: Repository branch of the consumer version.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - broker
    - publish
    - ${{ inputs.directory }}
    - --consumer-app-version
    - ${{ inputs.consumer_app_version }}
    - --branch
    - ${{ inputs.branch }}
    - --tag
    - ${{ inputs.branch }}
    - --no-auto-detect-version-properties
